Table: Person

+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| id          | int     |
| email       | varchar |
+-------------+---------+

id is the primary key (1column with unique values) for this table.
Each row of this table contains an email. The emails will not contain uppercase letters.
Write a solution to report all the duplicate emails. Note that it's guaranteed that the email field is not NULL.
Return the result table in any order.
The result format is in the following example.

 

Example 1:

Input: 
Person table:
+----+---------+
| id | email   |
+----+---------+
| 1  | a@b.com |
| 2  | c@d.com |
| 3  | a@b.com |
+----+---------+
Output: 
+---------+
| Email   |
+---------+
| a@b.com |
+---------+
Explanation: a@b.com is repeated two times.

In [6]:
import pandas as pd

In [7]:
data = [[1, 'a@b.com'], [2, 'c@d.com'], [3, 'a@b.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id':'Int64', 'email':'object'})

In [18]:
person_en = person.groupby('email').count().reset_index()
person_fin = person_en[person_en['id']>1][['email']]
display(person_fin)

     email
0  a@b.com

In [22]:
# versión mucho más óptima
def duplicate_emails(person: pd.DataFrame) -> pd.DataFrame:
    g = person.groupby('email').size().reset_index(name = 'email_count')
    #g = g[g['email_count'] > 1][["email"]]
    return g
df_filtered = duplicate_emails(person)
display(df_filtered)

     email  email_count
0  a@b.com            2
1  c@d.com            1